
// tag::all[]

[role="tabbed-block"]
====
.AWS / VMC
--
//***********************************
//* AWS DataStore Support           *
//***********************************

// tag::aws-datastore[]

AWS supports NetApp storage in the following configurations:

* FSx ONTAP as guest connected storage
* Cloud Volumes ONTAP (CVO) as guest connected storage
* FSx ONTAP as a supplemental NFS datastore

// tag::ehc-aws[]
View the detailed link:aws-guest.html[guest connect storage options for VMC].
View the detailed link:aws-native-nfs-datastore-option.html[supplemental NFS datastore options for VMC].
// end::ehc-aws[]

// tag::aws[]
View the detailed link:aws-guest.html[guest connect storage options for VMC].
View the detailed link:aws-native-nfs-datastore-option.html[supplemental NFS datastore options for VMC].
// end::aws[]
// end::aws-datastore[]
--
.Azure / AVS
--
//***********************************
//* Azure Datastore Support         *
//***********************************

// tag::azure-datastore[]

Azure supports NetApp storage in the following configurations:

* Azure NetApp Files (ANF) as guest connected storage
* Cloud Volumes ONTAP (CVO) as guest connected storage
* Azure NetApp Files (ANF) as a supplemental NFS datastore

// tag::ehc-azure[]
View the detailed link:azure-guest.html[guest connect storage options for AVS].
View the detailed link:azure-native-nfs-datastore-option.html[supplemental NFS datastore options for AVS].
// end::ehc-azure[]

// tag::azure[]
View the detailed link:azure-guest.html[guest connect storage options for AVS].
View the detailed link:azure-native-nfs-datastore-option.html[supplemental NFS datastore options for AVS].

// end::azure[]
// end::azure-datastore[]
--
.GCP / GCVE
--
//***********************************
//* Google Cloud Datastore Support  *
//***********************************

// tag::gcp-datastore[]

Google Cloud supports NetApp storage in the following configurations:

* Google Cloud NetApp Volumes as a supplemental NFS datastore
* Google Cloud NetApp Volumes as guest connected storage
* Cloud Volumes ONTAP (CVO) as guest connected storage


// tag::ehc-gcp[]
View the detailed link:gcp-guest.html[guest connect storage options for GCVE].
// end::ehc-gcp[]

// tag::gcp[]
View the detailed link:gcp-guest.html[guest connect storage options for GCVE].
// end::gcp[]

Read more about link:https://cloud.google.com/vmware-engine/docs/vmware-ecosystem/howto-cloud-volumes-datastores-gcve[Google Cloud NetApp Volumes datastore support for Google Cloud VMware Engine (Google documentation)^] 


// end::gcp-datastore[]
--
====

// end::all[]
